paths:
  input:
    dlr_file: data/input/dlr-lines.csv
    network_file: data/input/network-lines.csv
    pypsa_eur_file: data/input/pypsa-eur-lines.csv
    fifty_hertz_file: data/input/50hertz-lines.csv
    tennet_file: data/input/tennet-lines.csv
    boundary_file: data/input/germany-boundary.geojson
  output:
    matches_dir: output/matches/
    charts_dir: output/charts/
    maps_dir: output/maps/
  processed:
    clipped_dir: data/clipped/
matching:
  min_line_length_km: 1.0
  filter_voltage: 110.0
  dlr:
    buffer_distance: 0.02
    snap_distance: 0.009
    direction_threshold: 0.65
    enforce_voltage_matching: false
  pypsa_eur:
    max_distance: 0.0001
    max_hausdorff: 0.001
    relaxed_max_distance: 0.001
    relaxed_max_hausdorff: 0.005
  fifty_hertz:
    buffer_distance: 0.02
    snap_distance: 0.01
    direction_threshold: 0.65
    enforce_voltage_matching: true
  tennet:
    buffer_distance: 0.02
    snap_distance: 0.01
    direction_threshold: 0.65
    enforce_voltage_matching: true
visualization:
  map:
    start_zoom: 6
    tiles: CartoDB positron
    germany_center:
    - 51.1657
    - 10.4515
  charts:
    dpi: 300
    width: 10
    height: 8
logging:
  level: INFO
  file: output/grid_matching.log
